// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     coins.avsc
 */
package entities

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

func writeArrayCoin(r []Coin, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeCoin(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayCoinWrapper struct {
	Target *[]Coin
}

func (_ ArrayCoinWrapper) SetBoolean(v bool)                { panic("Unsupported operation") }
func (_ ArrayCoinWrapper) SetInt(v int32)                   { panic("Unsupported operation") }
func (_ ArrayCoinWrapper) SetLong(v int64)                  { panic("Unsupported operation") }
func (_ ArrayCoinWrapper) SetFloat(v float32)               { panic("Unsupported operation") }
func (_ ArrayCoinWrapper) SetDouble(v float64)              { panic("Unsupported operation") }
func (_ ArrayCoinWrapper) SetBytes(v []byte)                { panic("Unsupported operation") }
func (_ ArrayCoinWrapper) SetString(v string)               { panic("Unsupported operation") }
func (_ ArrayCoinWrapper) SetUnionElem(v int64)             { panic("Unsupported operation") }
func (_ ArrayCoinWrapper) Get(i int) types.Field            { panic("Unsupported operation") }
func (_ ArrayCoinWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ ArrayCoinWrapper) Finalize()                        {}
func (_ ArrayCoinWrapper) SetDefault(i int)                 { panic("Unsupported operation") }
func (r ArrayCoinWrapper) HintSize(s int) {
	if len(*r.Target) == 0 {
		*r.Target = make([]Coin, 0, s)
	}
}
func (r ArrayCoinWrapper) NullField(i int) {
	panic("Unsupported operation")
}

func (r ArrayCoinWrapper) AppendArray() types.Field {
	var v Coin
	v = NewCoin()

	*r.Target = append(*r.Target, v)
	return &types.Record{Target: &(*r.Target)[len(*r.Target)-1]}
}
