// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     coins.avsc
 */
package entities

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/container"
	"github.com/actgardner/gogen-avro/v10/vm"
)

func NewCoinsWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewCoins()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type CoinsReader struct {
	r io.Reader
	p *vm.Program
}

func NewCoinsReader(r io.Reader) (*CoinsReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewCoins()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &CoinsReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r CoinsReader) Read() (Coins, error) {
	t := NewCoins()
	err := vm.Eval(r.r, r.p, &t)
	return t, err
}
