// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     coins.avsc
 */
package entities

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/container"
	"github.com/actgardner/gogen-avro/v10/vm"
)

func NewCoinWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewCoin()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type CoinReader struct {
	r io.Reader
	p *vm.Program
}

func NewCoinReader(r io.Reader) (*CoinReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewCoin()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &CoinReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r CoinReader) Read() (Coin, error) {
	t := NewCoin()
	err := vm.Eval(r.r, r.p, &t)
	return t, err
}
