// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     coins.avsc
 */
package entities

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type Url struct {
	Id int32 `json:"id"`

	Type string `json:"type"`

	Link string `json:"link"`
}

const UrlAvroCRC64Fingerprint = "\x96\xd3\x19I\xaf\xe4Y\x04"

func NewUrl() Url {
	r := Url{}
	return r
}

func DeserializeUrl(r io.Reader) (Url, error) {
	t := NewUrl()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeUrlFromSchema(r io.Reader, schema string) (Url, error) {
	t := NewUrl()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeUrl(r Url, w io.Writer) error {
	var err error
	err = vm.WriteInt(r.Id, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Type, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Link, w)
	if err != nil {
		return err
	}
	return err
}

func (r Url) Serialize(w io.Writer) error {
	return writeUrl(r, w)
}

func (r Url) Schema() string {
	return "{\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"link\",\"type\":\"string\"}],\"name\":\"coin.io.coins.serialization.avro.Url\",\"type\":\"record\"}"
}

func (r Url) SchemaName() string {
	return "coin.io.coins.serialization.avro.Url"
}

func (_ Url) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ Url) SetInt(v int32)       { panic("Unsupported operation") }
func (_ Url) SetLong(v int64)      { panic("Unsupported operation") }
func (_ Url) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ Url) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ Url) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ Url) SetString(v string)   { panic("Unsupported operation") }
func (_ Url) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *Url) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.Int{Target: &r.Id}

		return w

	case 1:
		w := types.String{Target: &r.Type}

		return w

	case 2:
		w := types.String{Target: &r.Link}

		return w

	}
	panic("Unknown field index")
}

func (r *Url) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *Url) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ Url) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ Url) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ Url) HintSize(int)                     { panic("Unsupported operation") }
func (_ Url) Finalize()                        {}

func (_ Url) AvroCRC64Fingerprint() []byte {
	return []byte(UrlAvroCRC64Fingerprint)
}

func (r Url) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["id"], err = json.Marshal(r.Id)
	if err != nil {
		return nil, err
	}
	output["type"], err = json.Marshal(r.Type)
	if err != nil {
		return nil, err
	}
	output["link"], err = json.Marshal(r.Link)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *Url) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["id"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Id); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for id")
	}
	val = func() json.RawMessage {
		if v, ok := fields["type"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Type); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for type")
	}
	val = func() json.RawMessage {
		if v, ok := fields["link"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Link); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for link")
	}
	return nil
}
